version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - web-static:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      - supermarket-network

volumes:
  web-static:
    driver: local

networks:
  supermarket-network:
    driver: bridge